title: Tom Szwarcer
logo: /assets/img/logo.png
description: University of Oxford (Physics)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
url: https://tomszwarcer.github.io
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap